name: keepkapook
description: KeepKapook — โค้ชสร้างนิสัยการออมสำหรับวัยรุ่น
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  file_selector: ^1.1.0
  package_info_plus: ^10.2.1
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
